- name: Create Ava directory
  become: true
  ansible.builtin.file:
    path: "{{ to }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Download PyCharm
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ to }}/pycharm.tar.gz"
    # checksum: "sha256:{{ checksum_url }}"

- name: Extract PyCharm
  ansible.builtin.unarchive:
    src: "{{ to }}/pycharm.tar.gz"
    dest: "/var/ava/"
    creates: "/var/ava/pycharm-community-{{ version }}"
    remote_src: yes

- name: Launcher - Desktop file
  ansible.builtin.template:
    src: jetbrains-pycharm-ce.desktop.j2
    dest: "/home/{{ ansible_env.USER }}/.local/share/applications/jetbrains-pycharm-ce.desktop"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  become: true